### ISSUE TITLE
Githubページ作成

### ISSUE THREAD

**Issue by yu-kgr** [kanazawa-js/community-page#11]
- https://kanazawarb.github.io/ や https://kyoto.js.org/ を参考にしたGithubPageを作成する

## 達成したいこと

- Communityに関する最新情報が取得できること
- SNSやConnpassページへのリンクが用意できること
- イベントレポートがブログ形式で投稿できること
- 行動規約ページのようなものが固定で作れること

**Comment by yu-kgr** [comment]
MEMO 

- @kentaro-m さんが対応する

## Doneの定義

- community-pageに対してPRを提出。必要な要素が出揃っているかどうかを確認する

**Comment by tom-256** [comment]
ドメインどうしましょう
3回続いたら買う、それまでは無料ドメインとかにしますか？

**Comment by kentaro-m** [comment]
ひとまずLPのような簡易ページを用意中。最小限の構成で作り、機能を追加していくスタイルでいきたい。

<img width="1273" alt="スクリーンショット 2019-12-26 2 00 19" src="https://user-images.githubusercontent.com/7448569/71451957-b3172a80-27c2-11ea-98d0-ddbb85b9f92b.png">
<img width="1271" alt="スクリーンショット 2019-12-26 2 01 41" src="https://user-images.githubusercontent.com/7448569/71451960-b7dbde80-27c2-11ea-8f41-4993acdbb3b2.png">

**Comment by kentaro-m** [comment]
https://github.com/kanazawa-js/community-page/issues/21
イベントレポート対応のみ、別チケットにしました
