### ISSUE TITLE
アンケートの作成

### ISSUE THREAD

**Issue by kentaro-m** [kanazawa-js/community-page#22]
コミュニティにどういった需要があるのか知りたいです

**Comment by tom-256** [comment]
- 次回開催してほしいテーマはありますか？
a. LT会 b.もくもく会 c.ワークショップ d.交流会

**Comment by yu-kgr** [comment]
Connpassのアンケートなんですが、参加登録前じゃないとだめっぽかったので、
![image](https://user-images.githubusercontent.com/6540072/72593311-ff7c0300-3947-11ea-94dd-7fbd92a9497c.png)

今回はGoogleFormなどで行ったほうがよさそうでした。

**Comment by yu-kgr** [comment]
一旦、自分のアカウントにてアンケートの枠を作成したので、
お二人に編集権限をつけました。こちらを編集して貰えればよいかなと思います。
https://docs.google.com/forms/d/1Siw1T4LaYuzk8NYGfu8YqcIa4cKEsT6JlbpAHWuSDMw/edit

**Comment by tom-256** [comment]
@kentaro-m @yu-kgr 当日中にアンケート送ったほうが良いと思うので内容ご確認ください〜

**Comment by yu-kgr** [comment]
内容に文章的補足をいれてみました！

**Comment by tom-256** [comment]
作って集計したのでクローズ
