### ISSUE TITLE
次回のMeetup時に試してみたい題材を考える

### ISSUE THREAD

**Issue by yu-kgr** [kanazawa-js/community-page#32]
Meetup時に「もくもく&LT会」の他にも、

- 全員でひとつの題材をもくもく学習する会などあってもよいのではないか？

という事で、題材と進め方を検討するissueです。

## 題材案

- TypeScript
- Node.js
- React
- Next.js
- Gatsby

## 次のアクション

- [x] @kentaro-m / @tom-256 / @yu-kgr で相談する
  - コミュニティのコンセプトに沿う内容となるか
  - アンケートを流す場合は、内容をどうするか
- [x] どの題材が良いかのアンケートを何らかの媒体で作成

**Comment by tom-256** [comment]
雑なアンケート
https://kanazawajs.slack.com/archives/CSA7Z1EHW/p1590214236036700
