### ISSUE TITLE
行動規範の作成

### ISSUE THREAD

**Issue by yu-kgr** [kanazawa-js/community-page#5]
-githubPageができ次第、行動規約ページを用意する

**Comment by yu-kgr** [comment]
## 参考

- https://jp.communitycodeofconduct.com/
- https://github.com/SamirTalwar/communitycodeofconduct.com

**Comment by tom-256** [comment]
https://github.com/kanazawa-js/kanazawa-js.github.io/pull/15

**Comment by kentaro-m** [comment]
@tom-256 @yu-kgr 
こちら完了しても大丈夫でしょうか
