### ISSUE TITLE
Kzjsの運用について

### ISSUE THREAD

**Issue by yu-kgr** [kanazawa-js/community-page#59]
## 課題

1. 生活スタイルの変更により、土曜昼13-17時における @yu-kgr の参加が難しくなっており開催時の負担が偏っている
2. Meetup・社外交流という観点だと、新規の方が着ていない状況が続いている。
3. SlackからDiscordに移りしばらく経過。費用面では安定したが参加率としては低下しているためツールの見直しをしたほうがよいかどうか
4. 各自の所属が異なってくるが、運用に影響するかどうかについての確認

上記についてディスカッションの上、解決策などあれば出したい。

## 案

今の所、なんとなく思いついた所としては下記です。

- 開催頻度の見直しを検討する
- 日次の見直しの検討する
- もくもく会以外のコンテンツを積極的に行うようにする
- 懇親会にもっと力をいれる
- 基本ツールをSlackに戻して、リモート開催は別途ツールを検討する

**Comment by yu-kgr** [comment]
2は内容の話、3はツールの話である。一旦ココは後に話す。

一旦、1と4について議論する。

## 4について

4に関しては現時点ではわからない。（全く参加できなくなるようなことはなさそう）
参加にあたっては、Node.jsネタなどは出てきそう。

=> 様子を見つつコミット具合を見てく（11 ~ 12月あたりはあまり入れなさそう）

**Comment by yu-kgr** [comment]
## 1について

### 負担面

- 開催にあたる負担という所は感じていなかった（マツケン氏）
- 同意（tom氏）
- 開催前のほうが負担が大きい印象。

### 時間帯

- 各々が参加できる時間帯観点で検討しても良さそう。
  - 元々は○パクリでやってたのでそうなってた。
- 日程 : 平日, 土, 日 => どこでも良さそう

#### 日次 :  朝, 昼, 夜

- 昼の4時間
  - 内容次第で時間を増やす。
- 14 - 17 => 3時間
  - もくもくだけの場合は14 - 17時でも良いのではないか？

**Comment by yu-kgr** [comment]
## 2について

コンテンツ・宣伝の話し。

- 現状認識を合わせる
- Meetup・社外交流という観点
- 新規の方が着ていない状況が続いている

### As Is

* 透明性が低い（謎の集団化している） / 心理的安全が確保できていない？
  * やっていることがDiscordやGithub内で完結している
* コンテンツ不足（もくもく会だけでは参加したくない）

>参加者間で雑に交流することを大事にしたい

* 交流重視するよ
* インプット・アウトプットしたいよ！
* 各々がやりたいことを持ち込む形で、交流が生まれたという事実はあり。
* イベント全体の進行に関する説明やらが暗黙化している

--- 

### To Be : 

* フロントエンドの特定テーマに決めてのもくもく？モブプロ？を行うと良いのではないか。
  * 共通のテーマを同時にもくもくするのはどうか？
  * LTとかモブプロ、チュートリアルとか？
* イベント全体の進行に関する説明を最適化する

*追って考える*

HOWは後で考える

**Comment by yu-kgr** [comment]
## 3について

次回

**Comment by yu-kgr** [comment]
本日、下記について相談する

2. Meetup・社外交流という観点だと、新規の方が着ていない状況が続いている。

3. SlackからDiscordに移りしばらく経過。費用面では安定したが参加率としては低下しているためツールの見直しをしたほうがよいかどうか

**Comment by tom-256** [comment]
Discordのチャンネルを減らす

**Comment by kentaro-m** [comment]
https://discord.com/channels/769485511826997258/769492294595641374/810811358249091092
チャンネル説明を更新する

**Comment by kentaro-m** [comment]
ツールの用途

- Slack
    - イベント以外の日常的なコミュニケーション
    - テキストベースの運営相談 
- Discord
    - イベント当日のコミュニケーション
    - 音声ベースの運営相談

**Comment by tom-256** [comment]
音声だけDiscordを使う方針

**Comment by tom-256** [comment]
2番ネタ
> Meetup・社外交流という観点だと、新規の方が着ていない状況が続いている。

振り返り
https://jsconf.jp/2021/
モブチュートリアル実施
https://remix.run/
モブパフォーマンス改善
https://developers.cyberagent.co.jp/blog/archives/32747/

**Comment by yu-kgr** [comment]
一旦、こちらissueの課題は解決できている認識なのでクローズしますね
